# Generated by Django 2.2.8 on 2019-12-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191205_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.CharField(default='img/default_img.png', max_length=30),
        ),
    ]
