image: ubuntu

services:
  - docker:dind

stages:
  - deploy

before_script:
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'

  ## Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ## Create the SSH directory and give it the right permissions
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - ssh-keyscan 104.248.32.30 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  - git config --global user.email "turi.vajk@gmail.com"
  - git config --global user.name "vturi"


connect:
  stage: deploy
  script:
    - ssh -tt root@104.248.32.30 "/bin/bash -s  && exit " < deployscript.sh
  only:
    refs:
      - master