# Generated by Django 2.2.8 on 2019-12-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_path',
            field=models.CharField(default='img/default_img.png', max_length=30),
        ),
    ]
